hw_sharelane_tests
Galina313/SharelaneQA12J_Galina_Troichenko pull request #1
Opened 2024-11-12 19:30 UTC by Galina313

2024-11-12 20:07 UTC, voropa requested changes

2024-11-12 20:07 UTC, voropa commented on tests/sharelane.spec.ts
> +    this.timeout(10000);
Зачем тут timeout (10000) в начале теста?

2024-11-12 20:07 UTC, voropa commented on tests/sharelane.spec.ts
> +    try {
Используйте before/afterMethod для инициализации и закртия драйвера вместо try / finally

2024-11-12 20:07 UTC, voropa commented on tests/sharelane.spec.ts
> +    await driver.findElement(By.css('input[value="Login"]')).click();
В этом тесте нет ни одной  проверки, добавьте

2024-11-14 19:00 UTC, Galina313 commented on tests/sharelane.spec.ts
> +    this.timeout(10000);
Пофиксила)) действительно, не нужно))

2024-11-14 19:00 UTC, Galina313 commented on tests/sharelane.spec.ts
> +    try {
Пофиксила)

2024-11-14 19:00 UTC, Galina313 commented on tests/sharelane.spec.ts
> +    await driver.findElement(By.css('input[value="Login"]')).click();
Cделала)

2024-11-15 07:32 UTC, voropa requested changes

2024-11-15 07:32 UTC, voropa commented on tests/sharelane.spec.ts
> +    let driver = await new Builder().forBrowser(Browser.EDGE).build();
У вас иниициализаця драйвера уже есть в beforeEach(), зачем ее дублировать в начале теста еще раз?

2024-11-15 07:32 UTC, voropa commented on tests/sharelane.spec.ts
> +    let driver = await new Builder().forBrowser(Browser.EDGE).build();
То же самое

2024-11-16 14:25 UTC, voropa approved these changes

2024-11-18 13:42 UTC, merged